export const CHAT_STATES = Object.freeze({
  UNINITIALIZED: "UNINITIALIZED",
  IDLE: "IDLE",
  WAITING_FOR_START: "WAITING_FOR_START",
  GENERATING: "GENERATING",
  WAITING_FOR_END: "WAITING_FOR_END",
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
});

export const ERROR_CODES = Object.freeze({
  START_TIMEOUT: "START_TIMEOUT",
  RESPONSE_TIMEOUT: "RESPONSE_TIMEOUT",
  DOM_SELECTOR_ERROR: "DOM_SELECTOR_ERROR",
  FILESYSTEM_PERMISSION_ERROR: "FILESYSTEM_PERMISSION_ERROR",
  MARKDOWN_WRITE_ERROR: "MARKDOWN_WRITE_ERROR",
  PROJECT_NAME_EXTRACTION_ERROR: "PROJECT_NAME_EXTRACTION_ERROR",
  PROJECT_NOT_REGISTERED: "PROJECT_NOT_REGISTERED",
});

export const TIMING = Object.freeze({
  STATE_POLL_INTERVAL_MS: 100,
  START_CONFIRM_COUNT: 2,
  START_TIMEOUT_MS: 30_000,
  END_CONFIRM_COUNT: 5,
  ASSISTANT_STABLE_MS: 750,
  RESPONSE_TIMEOUT_MS: 600_000,
  STREAM_SAVE_DEBOUNCE_MS: 2_000,
  URL_POLL_INTERVAL_MS: 500,
});

export const STORAGE_KEYS = Object.freeze({
  SETTINGS: "outogptSettings",
  LAST_STATUS: "outogptLastStatus",
});

export const ROOT_HANDLE_KEY = "markdown-root";
export const DEBUG_PREFIX = "outoGPT";

